### ISSUE TITLE
Remove Margin from Worker Compensation/Manifesto page

### ISSUE THREAD

**Issue by pimato** [pimato/dxdao-landing-page#15]
Currently we have added margins to the whole page on full resolution but should only apply those margins if the width is < 1054. Everything above should not have any margin.

<img width="1164" alt="Bildschirmfoto 2020-10-20 um 10 49 57" src="https://user-images.githubusercontent.com/5337809/96563694-89377300-12c2-11eb-8ca3-5c997c0495c4.png">
<img width="1016" alt="Bildschirmfoto 2020-10-20 um 10 49 40" src="https://user-images.githubusercontent.com/5337809/96563706-8ccafa00-12c2-11eb-9556-022657f55ceb.png">

**Comment by Mi-Lan** [comment]
@pimato for the manifesto do you mean both margins and padding...or just margins?
