### ISSUE TITLE
Replace Mix.eth with Rails.eth

### ISSUE THREAD

**Issue by jpkcambridge** [pimato/dxdao-landing-page#23]
<img width="987" alt="Screen Shot 2020-10-20 at 10 42 45 AM" src="https://user-images.githubusercontent.com/874683/96602438-03ff8e80-12c1-11eb-944f-ebff44a1846f.png">

Since Mix.eth has not entered development yet, I think we should consider removing it from the home page.

In addition we should add Rails.eth

**Comment by Mi-Lan** [comment]
@jpkcambridge @pimato Any suggestions on what should be put as text for Rails? Or who to talk about that?
