### ISSUE TITLE
Change Link to DXtrust

### ISSUE THREAD

**Issue by jpkcambridge** [pimato/dxdao-landing-page#32]
“Get DXD” currently links to https://dxtrust.eth.link/#/

However, often the best place to get DXD is on exchanges.  We should update this somehow so that we don't mislead newcomers.  I think @pimato can provide guidance on how this should be done.  One idea I have is to also link to DXD trading on Swapr

**Comment by pimato** [comment]
lets do it like this:

- move the FAQ link to the Learn section in the top navigation
- Change the `Get DXD` button to `DXtrust.eth` and make it secondary styling
- Add a new button for Swapr

[Design Specification](https://www.figma.com/file/7splg18QAqjzr6XwSnXDMX/Landing?node-id=652%3A92)
